version: "3"

services:
  ansible2:
    image: ansible_v2
    volumes:
      - ../shared:/ansible
      - /var/run/docker.sock:/var/run/docker.sock
    command: tail -f  /dev/null
    container_name: ansible_container2

